package com.developerphil.adbidea.ui;

import com.developerphil.adbidea.adb.AdbFacade;
import com.intellij.openapi.project.Project;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import org.jetbrains.annotations.Nullable;

/**
 * Created by XQ Yang on 8/28/2018  4:13 PM.
 * Description :
 */

public class ApplicationManagementDialog extends JDialog {
    private JRadioButton mAllStatusRadioButton;
    private JRadioButton mDisabledRadioButton;
    private JRadioButton mEnabledRadioButton;
    private JRadioButton mAllTypeRadioButton;
    private JRadioButton mSystemRadioButton;
    private JRadioButton mThirdPartyRadioButton;
    private JCheckBox mShowApkFileCheckBox;
    private JCheckBox mShowInstallersCheckBox;
    private JCheckBox mContainsUninstalledCheckBox;
    private JButton mQueryButton;
    private JTextField tv_keyword;
    private JList mList1;
    private JButton mUninstallButton;
    private JButton mClearAppCacheDataButton;
    private JButton mRunningServicesButton;
    private JButton mViewDetailButton;
    private JButton mViewPathButton;
    private JPanel mPanel;
    private JScrollPane sp;

    private static final String PARAMETER_DISABLED = "-d ";
    private static final String PARAMETER_ENABLED = "-e ";
    private static final String PARAMETER_SYSTEM = "-s ";
    private static final String PARAMETER_THIRD_PARTY = "-3 ";
    private static final String PARAMETER_INSTALLER = "-i ";
    private static final String PARAMETER_UNINSTALLED = "-u ";
    private static final String PARAMETER_RELEVANCE_FILE = "-f ";

    private String keyWord = "";
    private String parameter = "";
    private Project mProject;

    public ApplicationManagementDialog(@Nullable Project project) {
        setContentPane($$$getRootComponent$$$());
        setModal(true);
        Dimension screensize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) screensize.getWidth() / 2 - getWidth() / 2;
        int y = (int) screensize.getHeight() / 2 - getHeight() / 2;
        setTitle("Adb Application Management");
        setLocation(x, y);
        mProject = project;

        mQueryButton.addActionListener(e -> {
            StringBuilder sb = new StringBuilder();
            if (mDisabledRadioButton.isSelected()) {
                sb.append(PARAMETER_DISABLED);
            } else if (mEnabledRadioButton.isSelected()) {
                sb.append(PARAMETER_ENABLED);
            }
            if (mSystemRadioButton.isSelected()) {
                sb.append(PARAMETER_SYSTEM);
            } else if (mThirdPartyRadioButton.isSelected()) {
                sb.append(PARAMETER_THIRD_PARTY);
            }
            if (mShowApkFileCheckBox.isSelected()) {
                sb.append(PARAMETER_RELEVANCE_FILE);
            }
            if (mShowInstallersCheckBox.isSelected()) {
                sb.append(PARAMETER_INSTALLER);
            }
            if (mContainsUninstalledCheckBox.isSelected()) {
                sb.append(PARAMETER_UNINSTALLED);
            }
            String keywordText = tv_keyword.getText();
            if (!Utils.isEmpty(keywordText)) {
                sb.append(keywordText);
            }
            AdbFacade.getAllApplicationList(mProject, sb.toString(), strings -> {
                mList1.setListData(strings.toArray());
                return null;
            });
        });
    }

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mPanel = new JPanel();
        mPanel.setLayout(new FormLayout("fill:338px:noGrow,left:4dlu:noGrow,fill:d:noGrow,left:4dlu:noGrow,fill:d:noGrow",
            "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        mPanel.setName("");
        mPanel.setBorder(BorderFactory.createTitledBorder("All Application"));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        CellConstraints cc = new CellConstraints();
        mPanel.add(panel1, cc.xy(1, 1));
        panel1.setBorder(BorderFactory.createTitledBorder("Other"));
        mShowApkFileCheckBox = new JCheckBox();
        mShowApkFileCheckBox.setText("Show Apk File");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(mShowApkFileCheckBox, gbc);
        mShowInstallersCheckBox = new JCheckBox();
        mShowInstallersCheckBox.setText("Show installers");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(mShowInstallersCheckBox, gbc);
        mContainsUninstalledCheckBox = new JCheckBox();
        mContainsUninstalledCheckBox.setText("Contains uninstalled");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(mContainsUninstalledCheckBox, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        mPanel.add(panel2, cc.xy(3, 1));
        panel2.setBorder(BorderFactory.createTitledBorder("Type"));
        mAllTypeRadioButton = new JRadioButton();
        mAllTypeRadioButton.setSelected(true);
        mAllTypeRadioButton.setText("All");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(mAllTypeRadioButton, gbc);
        mSystemRadioButton = new JRadioButton();
        mSystemRadioButton.setText("System");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(mSystemRadioButton, gbc);
        mThirdPartyRadioButton = new JRadioButton();
        mThirdPartyRadioButton.setText("Third-party");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(mThirdPartyRadioButton, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        panel3.setToolTipText("status");
        mPanel.add(panel3, cc.xy(5, 1));
        panel3.setBorder(BorderFactory.createTitledBorder("Status"));
        mAllStatusRadioButton = new JRadioButton();
        mAllStatusRadioButton.setSelected(true);
        mAllStatusRadioButton.setText("All");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(mAllStatusRadioButton, gbc);
        mEnabledRadioButton = new JRadioButton();
        mEnabledRadioButton.setText("enabled");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(mEnabledRadioButton, gbc);
        mDisabledRadioButton = new JRadioButton();
        mDisabledRadioButton.setText("disabled");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel3.add(mDisabledRadioButton, gbc);
        mQueryButton = new JButton();
        mQueryButton.setText("Query");
        mPanel.add(mQueryButton, cc.xy(5, 3));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        mPanel.add(panel4, cc.xyw(1, 3, 3));
        final JLabel label1 = new JLabel();
        label1.setText("Name Filter :");
        panel4.add(label1,
            new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null,
                null, 0, false));
        tv_keyword = new JTextField();
        panel4.add(tv_keyword,
            new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED,
                null, new Dimension(150, -1), null, 0, false));
        final JPanel panel5 = new JPanel();
        panel5.setLayout(
            new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow",
                "center:d:noGrow"));
        mPanel.add(panel5, cc.xyw(1, 7, 5));
        mUninstallButton = new JButton();
        mUninstallButton.setText("Uninstall");
        panel5.add(mUninstallButton, cc.xy(1, 1));
        mClearAppCacheDataButton = new JButton();
        mClearAppCacheDataButton.setText("Clear app  cache  data");
        panel5.add(mClearAppCacheDataButton, cc.xy(3, 1));
        mRunningServicesButton = new JButton();
        mRunningServicesButton.setText("Running Services");
        panel5.add(mRunningServicesButton, cc.xy(5, 1));
        mViewDetailButton = new JButton();
        mViewDetailButton.setText("View Detail");
        panel5.add(mViewDetailButton, cc.xy(7, 1));
        mViewPathButton = new JButton();
        mViewPathButton.setText("View Path");
        panel5.add(mViewPathButton, cc.xy(9, 1));
        sp = new JScrollPane();
        mPanel.add(sp, cc.xyw(1, 5, 5, CellConstraints.FILL, CellConstraints.FILL));
        mList1 = new JList();
        sp.setViewportView(mList1);
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(mDisabledRadioButton);
        buttonGroup.add(mAllStatusRadioButton);
        buttonGroup.add(mEnabledRadioButton);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(mAllTypeRadioButton);
        buttonGroup.add(mSystemRadioButton);
        buttonGroup.add(mThirdPartyRadioButton);
    }

    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$() {
        return mPanel;
    }
}
